# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "788925c2e21b7089cd3f09835b2c614b"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "VibeSzn Discount Functions"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
