api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "app-home"
type = "ui_extension"

  # Only 1 target can be specified for an app-home extension.
  [[extensions.targeting]]
  module = "./src/AppHome.jsx"
  target = "admin.app.home.render"
