api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "hide-free-shipping"
uid = "e41812fb-edc9-c518-ec2c-97907ce032a7a3b11530"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
